// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlGjPFLX6Iiwn_YVUiFQKc7XUR9iYKLs',
    appId: '1:446535163192:web:1b11ef3f5c45b345f535cd',
    messagingSenderId: '446535163192',
    projectId: 'kurdpoint-42fe9',
    authDomain: 'kurdpoint-42fe9.firebaseapp.com',
    storageBucket: 'kurdpoint-42fe9.firebasestorage.app',
    measurementId: 'G-WEEBDRPYLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGUdxa5zbaOq6Ww14mfoGDNWbSRO_LvY0',
    appId: '1:446535163192:android:4b18c7541bfacb9ef535cd',
    messagingSenderId: '446535163192',
    projectId: 'kurdpoint-42fe9',
    storageBucket: 'kurdpoint-42fe9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRwNDQjvvI840Y3AugXVs4HIKbZuym-Y',
    appId: '1:446535163192:ios:c86c1c64f0431862f535cd',
    messagingSenderId: '446535163192',
    projectId: 'kurdpoint-42fe9',
    storageBucket: 'kurdpoint-42fe9.firebasestorage.app',
    iosBundleId: 'com.kurdpoint.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRwNDQjvvI840Y3AugXVs4HIKbZuym-Y',
    appId: '1:446535163192:ios:c86c1c64f0431862f535cd',
    messagingSenderId: '446535163192',
    projectId: 'kurdpoint-42fe9',
    storageBucket: 'kurdpoint-42fe9.firebasestorage.app',
    iosBundleId: 'com.kurdpoint.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmlGjPFLX6Iiwn_YVUiFQKc7XUR9iYKLs',
    appId: '1:446535163192:web:e1a9ac8aec433b15f535cd',
    messagingSenderId: '446535163192',
    projectId: 'kurdpoint-42fe9',
    authDomain: 'kurdpoint-42fe9.firebaseapp.com',
    storageBucket: 'kurdpoint-42fe9.firebasestorage.app',
    measurementId: 'G-55C9PHFV9R',
  );

}
